# Generated by Django 6.0.2 on 2026-02-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos/'),
        ),
    ]
