# Generated by Django 6.0.2 on 2026-02-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_repuesto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
