# Generated by Django 6.0.2 on 2026-02-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coupon_favorite_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_status', 'Cambio de estado de orden'), ('stock_low', 'Stock bajo'), ('stock_high', 'Stock alto')], default='order_status', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.repuesto'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.order'),
        ),
    ]
