# Generated by Django 6.0.2 on 2026-02-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='repuestos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.repuesto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
