# Generated by Django 5.2.4 on 2025-07-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop_app', '0002_alter_user_managers_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
