# Generated by Django 5.2.4 on 2025-07-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop_app', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iis_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
