services:
  - type: web
    name: carshop-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend_project.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
